"""Report Generator — Generate PDF mission report."""

import json
from pathlib import Path


def generate_report_text(config: dict) -> str:
    """Generate a text mission report from configuration."""
    mission = config.get("mission", {})
    satellite = config.get("satellite", {})
    orbit = config.get("orbit", {})
    subsystems = config.get("subsystems", {})

    lines = [
        f"{'=' * 60}",
        f"  MISSION REPORT: {mission.get('name', 'UniSat-1')}",
        f"{'=' * 60}",
        f"",
        f"Version: {mission.get('version', '1.0.0')}",
        f"Operator: {mission.get('operator', 'N/A')}",
        f"Launch Date: {mission.get('launch_date', 'TBD')}",
        f"",
        f"--- SATELLITE ---",
        f"Form Factor: {satellite.get('form_factor', '3U')}",
        f"Mass: {satellite.get('mass_kg', 0)} kg",
        f"Dimensions: {satellite.get('dimensions_mm', [])} mm",
        f"",
        f"--- ORBIT ---",
        f"Type: {orbit.get('type', 'LEO')}",
        f"Altitude: {orbit.get('altitude_km', 0)} km",
        f"Inclination: {orbit.get('inclination_deg', 0)}°",
        f"",
        f"--- SUBSYSTEMS ---",
    ]

    for name, cfg in subsystems.items():
        enabled = cfg.get("enabled", False) if isinstance(cfg, dict) else cfg
        status = "ENABLED" if enabled else "DISABLED"
        lines.append(f"  {name.upper():.<20} {status}")

    lines.extend([
        f"",
        f"--- GROUND STATION ---",
        f"Location: {config.get('ground_station', {}).get('location', {}).get('name', 'N/A')}",
        f"",
        f"{'=' * 60}",
        f"  Report generated by UniSat Configurator",
        f"{'=' * 60}",
    ])

    return "\n".join(lines)


def save_report(config: dict, output_path: str = "mission_report.txt") -> str:
    """Save mission report to file."""
    report = generate_report_text(config)
    Path(output_path).write_text(report, encoding="utf-8")
    return output_path
