/**
 * @file test_ax25_golden.c
 * @brief Cross-impl golden vector verification (REQ-AX25-015).
 *
 * Consumes tests/golden/ax25_vectors.inc (generated by
 * scripts/gen_golden_vectors.py from the Python reference). For each
 * encode vector, runs the C encoder and asserts byte-identical output.
 */

#include "unity/unity.h"
#include "ax25.h"
#include "ax25_vectors.inc"
#include <string.h>

void setUp(void) {}
void tearDown(void) {}

static ax25_status_t status_from_name(const char *name) {
  if (strcmp(name, "AX25_ERR_ADDRESS_INVALID") == 0)  return AX25_ERR_ADDRESS_INVALID;
  if (strcmp(name, "AX25_ERR_FCS_MISMATCH") == 0)     return AX25_ERR_FCS_MISMATCH;
  if (strcmp(name, "AX25_ERR_CONTROL_INVALID") == 0)  return AX25_ERR_CONTROL_INVALID;
  if (strcmp(name, "AX25_ERR_PID_INVALID") == 0)      return AX25_ERR_PID_INVALID;
  if (strcmp(name, "AX25_ERR_INFO_TOO_LONG") == 0)    return AX25_ERR_INFO_TOO_LONG;
  if (strcmp(name, "AX25_ERR_FRAME_TOO_LONG") == 0)   return AX25_ERR_FRAME_TOO_LONG;
  if (strcmp(name, "AX25_ERR_STUFFING_VIOLATION") == 0) return AX25_ERR_STUFFING_VIOLATION;
  return AX25_OK;
}

void test_encode_vectors_match_python(void) {
  int encode_checked = 0;
  for (size_t i = 0; i < AX25_GOLDEN_VECTOR_COUNT; i++) {
    const ax25_golden_t *v = &AX25_GOLDEN_VECTORS[i];
    if (v->kind != 0) continue;  /* encode vectors only */

    ax25_address_t dst = { .ssid = v->dst_ssid };
    ax25_address_t src = { .ssid = v->src_ssid };
    strncpy(dst.callsign, v->dst_callsign, 6);
    dst.callsign[6] = '\0';
    strncpy(src.callsign, v->src_callsign, 6);
    src.callsign[6] = '\0';

    uint8_t out[AX25_MAX_FRAME_BYTES];
    size_t n = 0;
    ax25_status_t st = ax25_encode_ui_frame(&dst, &src, 0xF0,
        v->info, v->info_len, out, sizeof(out), &n);

    if (st != AX25_OK) {
      printf("\nvector %zu (%s): encode failed with status %d\n",
          i, v->description, (int)st);
      TEST_ASSERT_EQUAL(AX25_OK, st);
    }
    TEST_ASSERT_EQUAL((int)v->encoded_len, (int)n);
    TEST_ASSERT_EQUAL_MEMORY(v->encoded, out, n);
    encode_checked++;
  }
  TEST_ASSERT_TRUE(encode_checked >= 20);
}

void test_decode_raw_vectors_match_python(void) {
  int decode_checked = 0;
  for (size_t i = 0; i < AX25_GOLDEN_VECTOR_COUNT; i++) {
    const ax25_golden_t *v = &AX25_GOLDEN_VECTORS[i];
    if (v->kind != 1) continue;  /* decode_raw vectors only */

    ax25_ui_frame_t out;
    ax25_status_t st = ax25_decode_ui_frame(v->raw_body, v->raw_body_len, &out);
    ax25_status_t expected = status_from_name(v->expected_status);
    if (st != expected) {
      printf("\nvector %zu (%s): expected status %s (%d), got %d\n",
          i, v->description, v->expected_status, (int)expected, (int)st);
    }
    TEST_ASSERT_EQUAL(expected, st);
    decode_checked++;
  }
  TEST_ASSERT_TRUE(decode_checked >= 4);
}

int main(void) {
  UNITY_BEGIN();
  RUN_TEST(test_encode_vectors_match_python);
  RUN_TEST(test_decode_raw_vectors_match_python);
  return UNITY_END();
}
