"""Generate docs/verification/ax25_trace_matrix.md.

Scans the C and Python test files for REQ-AX25-NNN annotations and
produces a table mapping each requirement to the tests that exercise it.

Run:  python scripts/gen_trace_matrix.py
"""

from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TEST_DIRS = [
    REPO / "firmware" / "tests",
    REPO / "ground-station" / "tests",
    REPO / "firmware" / "stm32" / "Drivers" / "AX25",  # header docstrings
]

REQ_RE = re.compile(r"REQ-AX25-(\d{3})")
TEST_RE = re.compile(
    r"def (test_\w+)|void (test_\w+)\s*\("
)


def scan() -> dict[str, list[tuple[Path, int, str]]]:
    hits: dict[str, list[tuple[Path, int, str]]] = {}
    for root in TEST_DIRS:
        for path in root.rglob("*"):
            if path.suffix not in (".c", ".py", ".h"):
                continue
            text = path.read_text(errors="ignore")
            current = "<file>"
            for i, line in enumerate(text.splitlines(), 1):
                m = TEST_RE.search(line)
                if m:
                    current = m.group(1) or m.group(2)
                for req_m in REQ_RE.finditer(line):
                    key = f"REQ-AX25-{req_m.group(1)}"
                    hits.setdefault(key, []).append(
                        (path.relative_to(REPO), i, current)
                    )
    return hits


def main() -> None:
    hits = scan()
    out = [
        "# AX.25 Verification Matrix",
        "",
        "Auto-generated by `scripts/gen_trace_matrix.py`.",
        "Regenerate after adding or renaming tests.",
        "",
        "| REQ | Test file | Line | Symbol |",
        "|-----|-----------|------|--------|",
    ]
    for req in sorted(hits):
        for path, line, symbol in hits[req]:
            path_str = str(path).replace("\\", "/")
            out.append(f"| {req} | `{path_str}` | {line} | `{symbol}` |")
    out.append("")
    out.append(f"**Unique requirements with coverage:** {len(hits)}")
    total_links = sum(len(v) for v in hits.values())
    out.append(f"**Total references:** {total_links}")

    out_path = REPO / "docs" / "verification" / "ax25_trace_matrix.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out) + "\n")
    print(f"Wrote {total_links} references for {len(hits)} requirements "
          f"to {out_path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
